linters:
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert # https://github.com/gostaticanalysis/forcetypeassert#forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - err113
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - goprintffuncname # https://github.com/jirfag/go-printf-func-name#go-printf-func-name
    - grouper
    - gosec
    - importas
    - interfacebloat
    - ireturn
    - lll
    - makezero # https://github.com/ashanbrown/makezero#purpose
    - misspell
    - nakedret
    - nestif
    - nilerr # https://github.com/gostaticanalysis/nilerr#nilerr
    - nilnil # https://github.com/Antonboom/nilnil#motivation
    - nolintlint # https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md#purpose
    - paralleltest
    - prealloc # https://github.com/alexkohler/prealloc#purpose
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tparallel # https://github.com/moricho/tparallel
    - unconvert # https://github.com/mdempsky/unconvert#usage
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl # https://github.com/bombsimon/wsl/blob/master/doc/rules.md

linters-settings:
  wsl:
    allow-assign-and-anything: true
issues:
  exclude-use-default: false
  exclude:
    - ST1000
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
    - source: "ListTransactions"
      linters:
        - funlen
    - source: "^func New\\(db \\*pgxpool\\.Pool\\) Repository"
      linters:
        - ireturn
    - source: "getExecutor"
      linters:
        - ireturn
    - path: _test\.go
      linters:
        - funlen